services:
  - type: web
    name: warriorhr-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false # Set this in the Render dashboard
      - key: JWT_SECRET
        sync: false # Set this in the Render dashboard
      - key: ADMIN_ROUTE
        value: /api/admin
